// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jloom6/phishql/mapper (interfaces: Interface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	phishql "github.com/jloom6/phishql/.gen/proto/jloom6/phishql"
	structs "github.com/jloom6/phishql/structs"
	reflect "reflect"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// ArtistsToProto mocks base method
func (m *MockInterface) ArtistsToProto(arg0 []structs.Artist) []*phishql.Artist {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArtistsToProto", arg0)
	ret0, _ := ret[0].([]*phishql.Artist)
	return ret0
}

// ArtistsToProto indicates an expected call of ArtistsToProto
func (mr *MockInterfaceMockRecorder) ArtistsToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArtistsToProto", reflect.TypeOf((*MockInterface)(nil).ArtistsToProto), arg0)
}

// GraphQLShowsToProto mocks base method
func (m *MockInterface) GraphQLShowsToProto(arg0 map[string]interface{}) (*phishql.GetShowsRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GraphQLShowsToProto", arg0)
	ret0, _ := ret[0].(*phishql.GetShowsRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GraphQLShowsToProto indicates an expected call of GraphQLShowsToProto
func (mr *MockInterfaceMockRecorder) GraphQLShowsToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GraphQLShowsToProto", reflect.TypeOf((*MockInterface)(nil).GraphQLShowsToProto), arg0)
}

// ProtoToArtists mocks base method
func (m *MockInterface) ProtoToArtists(arg0 []*phishql.Artist) []structs.Artist {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToArtists", arg0)
	ret0, _ := ret[0].([]structs.Artist)
	return ret0
}

// ProtoToArtists indicates an expected call of ProtoToArtists
func (mr *MockInterfaceMockRecorder) ProtoToArtists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToArtists", reflect.TypeOf((*MockInterface)(nil).ProtoToArtists), arg0)
}

// ProtoToGetArtistsRequest mocks base method
func (m *MockInterface) ProtoToGetArtistsRequest(arg0 *phishql.GetArtistsRequest) structs.GetArtistsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToGetArtistsRequest", arg0)
	ret0, _ := ret[0].(structs.GetArtistsRequest)
	return ret0
}

// ProtoToGetArtistsRequest indicates an expected call of ProtoToGetArtistsRequest
func (mr *MockInterfaceMockRecorder) ProtoToGetArtistsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToGetArtistsRequest", reflect.TypeOf((*MockInterface)(nil).ProtoToGetArtistsRequest), arg0)
}

// ProtoToGetShowsRequest mocks base method
func (m *MockInterface) ProtoToGetShowsRequest(arg0 *phishql.GetShowsRequest) structs.GetShowsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToGetShowsRequest", arg0)
	ret0, _ := ret[0].(structs.GetShowsRequest)
	return ret0
}

// ProtoToGetShowsRequest indicates an expected call of ProtoToGetShowsRequest
func (mr *MockInterfaceMockRecorder) ProtoToGetShowsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToGetShowsRequest", reflect.TypeOf((*MockInterface)(nil).ProtoToGetShowsRequest), arg0)
}

// ProtoToGetSongsRequest mocks base method
func (m *MockInterface) ProtoToGetSongsRequest(arg0 *phishql.GetSongsRequest) structs.GetSongsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToGetSongsRequest", arg0)
	ret0, _ := ret[0].(structs.GetSongsRequest)
	return ret0
}

// ProtoToGetSongsRequest indicates an expected call of ProtoToGetSongsRequest
func (mr *MockInterfaceMockRecorder) ProtoToGetSongsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToGetSongsRequest", reflect.TypeOf((*MockInterface)(nil).ProtoToGetSongsRequest), arg0)
}

// ProtoToGetTagsRequest mocks base method
func (m *MockInterface) ProtoToGetTagsRequest(arg0 *phishql.GetTagsRequest) structs.GetTagsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToGetTagsRequest", arg0)
	ret0, _ := ret[0].(structs.GetTagsRequest)
	return ret0
}

// ProtoToGetTagsRequest indicates an expected call of ProtoToGetTagsRequest
func (mr *MockInterfaceMockRecorder) ProtoToGetTagsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToGetTagsRequest", reflect.TypeOf((*MockInterface)(nil).ProtoToGetTagsRequest), arg0)
}

// ProtoToGetToursRequest mocks base method
func (m *MockInterface) ProtoToGetToursRequest(arg0 *phishql.GetToursRequest) structs.GetToursRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToGetToursRequest", arg0)
	ret0, _ := ret[0].(structs.GetToursRequest)
	return ret0
}

// ProtoToGetToursRequest indicates an expected call of ProtoToGetToursRequest
func (mr *MockInterfaceMockRecorder) ProtoToGetToursRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToGetToursRequest", reflect.TypeOf((*MockInterface)(nil).ProtoToGetToursRequest), arg0)
}

// ProtoToGetVenuesRequest mocks base method
func (m *MockInterface) ProtoToGetVenuesRequest(arg0 *phishql.GetVenuesRequest) structs.GetVenuesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToGetVenuesRequest", arg0)
	ret0, _ := ret[0].(structs.GetVenuesRequest)
	return ret0
}

// ProtoToGetVenuesRequest indicates an expected call of ProtoToGetVenuesRequest
func (mr *MockInterfaceMockRecorder) ProtoToGetVenuesRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToGetVenuesRequest", reflect.TypeOf((*MockInterface)(nil).ProtoToGetVenuesRequest), arg0)
}

// ProtoToShows mocks base method
func (m *MockInterface) ProtoToShows(arg0 []*phishql.Show) ([]structs.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToShows", arg0)
	ret0, _ := ret[0].([]structs.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProtoToShows indicates an expected call of ProtoToShows
func (mr *MockInterfaceMockRecorder) ProtoToShows(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToShows", reflect.TypeOf((*MockInterface)(nil).ProtoToShows), arg0)
}

// ProtoToSongs mocks base method
func (m *MockInterface) ProtoToSongs(arg0 []*phishql.Song) []structs.Song {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToSongs", arg0)
	ret0, _ := ret[0].([]structs.Song)
	return ret0
}

// ProtoToSongs indicates an expected call of ProtoToSongs
func (mr *MockInterfaceMockRecorder) ProtoToSongs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToSongs", reflect.TypeOf((*MockInterface)(nil).ProtoToSongs), arg0)
}

// ProtoToTags mocks base method
func (m *MockInterface) ProtoToTags(arg0 []*phishql.Tag) []structs.Tag {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToTags", arg0)
	ret0, _ := ret[0].([]structs.Tag)
	return ret0
}

// ProtoToTags indicates an expected call of ProtoToTags
func (mr *MockInterfaceMockRecorder) ProtoToTags(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToTags", reflect.TypeOf((*MockInterface)(nil).ProtoToTags), arg0)
}

// ProtoToTours mocks base method
func (m *MockInterface) ProtoToTours(arg0 []*phishql.Tour) []structs.Tour {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToTours", arg0)
	ret0, _ := ret[0].([]structs.Tour)
	return ret0
}

// ProtoToTours indicates an expected call of ProtoToTours
func (mr *MockInterfaceMockRecorder) ProtoToTours(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToTours", reflect.TypeOf((*MockInterface)(nil).ProtoToTours), arg0)
}

// ProtoToVenues mocks base method
func (m *MockInterface) ProtoToVenues(arg0 []*phishql.Venue) []structs.Venue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoToVenues", arg0)
	ret0, _ := ret[0].([]structs.Venue)
	return ret0
}

// ProtoToVenues indicates an expected call of ProtoToVenues
func (mr *MockInterfaceMockRecorder) ProtoToVenues(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoToVenues", reflect.TypeOf((*MockInterface)(nil).ProtoToVenues), arg0)
}

// ShowsToProto mocks base method
func (m *MockInterface) ShowsToProto(arg0 []structs.Show) ([]*phishql.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowsToProto", arg0)
	ret0, _ := ret[0].([]*phishql.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowsToProto indicates an expected call of ShowsToProto
func (mr *MockInterfaceMockRecorder) ShowsToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowsToProto", reflect.TypeOf((*MockInterface)(nil).ShowsToProto), arg0)
}

// SongsToProto mocks base method
func (m *MockInterface) SongsToProto(arg0 []structs.Song) []*phishql.Song {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SongsToProto", arg0)
	ret0, _ := ret[0].([]*phishql.Song)
	return ret0
}

// SongsToProto indicates an expected call of SongsToProto
func (mr *MockInterfaceMockRecorder) SongsToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SongsToProto", reflect.TypeOf((*MockInterface)(nil).SongsToProto), arg0)
}

// TagsToProto mocks base method
func (m *MockInterface) TagsToProto(arg0 []structs.Tag) []*phishql.Tag {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagsToProto", arg0)
	ret0, _ := ret[0].([]*phishql.Tag)
	return ret0
}

// TagsToProto indicates an expected call of TagsToProto
func (mr *MockInterfaceMockRecorder) TagsToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsToProto", reflect.TypeOf((*MockInterface)(nil).TagsToProto), arg0)
}

// ToursToProto mocks base method
func (m *MockInterface) ToursToProto(arg0 []structs.Tour) []*phishql.Tour {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToursToProto", arg0)
	ret0, _ := ret[0].([]*phishql.Tour)
	return ret0
}

// ToursToProto indicates an expected call of ToursToProto
func (mr *MockInterfaceMockRecorder) ToursToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToursToProto", reflect.TypeOf((*MockInterface)(nil).ToursToProto), arg0)
}

// VenuesToProto mocks base method
func (m *MockInterface) VenuesToProto(arg0 []structs.Venue) []*phishql.Venue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VenuesToProto", arg0)
	ret0, _ := ret[0].([]*phishql.Venue)
	return ret0
}

// VenuesToProto indicates an expected call of VenuesToProto
func (mr *MockInterfaceMockRecorder) VenuesToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VenuesToProto", reflect.TypeOf((*MockInterface)(nil).VenuesToProto), arg0)
}
